name: Building Gitbook
run-name: ${{ github.actor }} is building Gitbook
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 10
          cache: 'node-modules'
          cache-dependency-path: ./package-lock.json
          
      - name: Install dependencies
        run: |
          npm install -g gitbook-cli
          
      - name: try install sitemap-general plugins
        run: |
          npm install -g gitbook-plugin-sitemap-general
        
      - name: GitBook install plugins
        run: |
          gitbook install
          
      - name: Init GitBook
        run: |
          gitbook init
          
      - name: Build GitBook in docs directory
        run: |
          gitbook build ./ ./docs
             
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/

